env: 
  NODE_ENV: 'production'
  LOG_LEVEL: 'debug'
core: 
  host: '0.0.0.0'
  port: 3000
  baseUrl: 'http://localhost:3000'
  auth:
    JWT_SECRET_KEY: 'rwnEBlTPIFyPlJrpsjK2BBQM/ZVAZQwzm5jsv5Jy0CMC8U8eIX+vuJsGn4GPhzE8NhbEhCrlvfwKvPUbNhN86Q=='
    JWT_EXPIRATION_TIME: '12h'
  crossDomain: 
    allowedOrigins: ['https://test.com', 'https://cdn.test.com', 'https://admin.test.com', 'https://api.test.com']
    allowedReferer: 'test.com'

db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  database: 'nestjs'
  username: 'postgres'
  password: ''
  synchronize: true
  logging: true
  
mail:
  enabled: true                    # 是否开启邮箱发送功能
  transport:
    host: 'smtp.exmail.163.com'
    port: 465
    secure: false
    auth:
      user: 'moocss@163.com'
      pass: 'pass'
  defaults:
    from: 'moocss@126.com'
  templateDir: './src/email-templates'
  mailerType: 0 # 0: default mailer, 1: sendgrid mailer, 2: extend mailer
    
cache:
  redis:
    client:
      host: '127.0.0.1'
      port: 6379
      password: 'pass'
      db: '0'