env: 
  NODE_ENV: 'dev'
  LOG_LEVEL: 'debug'
  NODE_TLS_REJECT_UNAUTHORIZED: 0
core: 
  host: '0.0.0.0'
  port: 3000
  baseUrl: 'http://localhost:300'
  passport: 
    local: 
      usernameField: 'name'
      passwordField: 'pass'
    github: 
      key: 'test'
      secret: 'test'
  crossDomain: 
    allowedOrigins: ['https://test.com', 'https://cdn.test.com', 'https://admin.test.com', 'https://api.test.com']
    allowedReferer: 'test.com'
  auth:
    enable: true
    expiresIn: 3600
    jwtTokenSecret: ''

db:
  dialect: 'mysql'
  host: 'localhost'
  prot: 3306
  database: 'db_name'
  username: 'root'
  password: 'root'
  logMode: true
  
mail:
  enabled: true                    # 是否开启邮箱发送功能
  transport:
    host: <smtp_host>
    port: <smtp_port_number>
    secure: false
    auth:
      user: <email>
      pass: <pass>
  defaults:
    from: <email>
  sendGrid:
    apiKey: <api_key>
  templateDir: './src/email-templates'
  mailerType: 0 # 0: default mailer, 1: sendgrid mailer, 2: extend mailer
    
cache:
  redis:
    client:
      host: '127.0.0.1'
      port: 6379
      password: ''
      db: '0'